version: '1.0'
name: ci
displayName: ci
triggers:
  trigger: auto
  pr:
    branches:
      precise:
        - main
  push:
    branches:
      precise:
        - main

variables:
  XMAKE_MAIN_REPO: https://gitee.com/tboox/xmake-repo.git
  XMAKE_BINARY_REPO: https://gitee.com/xmake-mirror/build-artifacts.git
  XMAKE_ROOT: 'y'

stages:
  - name: build_and_test 
    displayName: build_and_test
    strategy: fast
    trigger: auto
    executor: []
    steps:
      - step: build@gcc
        name: build
        displayName: Run S7 SRFI tests
        gccVersion: '10.3'
        commands:
          - wget https://gitee.com/XmacsLabs/mogan/attach_files/1813514/download -O /tmp/xmake.deb
          - sha1sum /tmp/xmake.deb | grep ac3629bd0fa66f179aef35dc00b7a1c89735651a
          - apt install /tmp/xmake.deb
          - sed -i '/github\.com/d' xmake/packages/s/s7/xmake.lua
          - xmake repo -u
          - xmake config -vD --yes
          - xmake b goldfish
          - find tests | grep "test.scm" | xargs -I% bin/goldfish %
        caches: []
        notify: []
        strategy:
          retry: '0'
          stepTimeout: 30
