name: CI on Fedora 41
on:
  push:
    branches: [ main ]
    paths:
      - 'goldfish/**'
      - 'src/**'
      - 'tests/**'
      - 'xmake/**'
      - 'xmake.lua'
      - '.github/workflows/ci-fedora.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'goldfish/**'
      - 'src/**'
      - 'tests/**'
      - 'xmake/**'
      - 'xmake.lua'
      - '.github/workflows/ci-fedora.yml'

env:
  XMAKE_ROOT: y
  DEBIAN_FRONTEND: noninteractive

jobs:
  build:
    container: fedora:41
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: true
    steps:
      - name: Install dependencies
        run: |
          sudo dnf update -y
          sudo dnf install -y gcc g++ xmake git unzip curl
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: git add safe directory
        run: git config --global --add safe.directory '*'

      - name: de-gitee
        run: sed -i '/gitee\.com/d' xmake/packages/s/s7/xmake.lua

      - name: set XMAKE_GLOBALDIR
        run: echo "XMAKE_GLOBALDIR=${{ runner.workspace }}/xmake-global" >> $GITHUB_ENV

      - name: xmake repo --update
        run: xmake repo --update

      - name: cache packages from xrepo
        uses: actions/cache@v3
        with:
          path: |
            ${{ env.XMAKE_GLOBALDIR }}/.xmake/packages
          key: ${{ runner.os }}-xrepo-${{ hashFiles('**/xmake.lua') }}

      - name: config
        run: xmake config -vD --policies=build.ccache -o tmp/build -m releasedbg --yes

      - name: build
        run: xmake build --yes -vD goldfish

      - name: run tests
        run: bin/goldfish -l tests/test_all.scm

